//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Settings {
    
    private string scanPathField;
    
    private bool deleteGenericField;
    
    private bool dateBiasField;
    
    private string[] excludedGenericShowField;
    
    private string[] preferredChannelField;
    
    private string logField;
    
    /// <remarks/>
    public string ScanPath {
        get {
            return this.scanPathField;
        }
        set {
            this.scanPathField = value;
        }
    }
    
    /// <remarks/>
    public bool DeleteGeneric {
        get {
            return this.deleteGenericField;
        }
        set {
            this.deleteGenericField = value;
        }
    }
    
    /// <remarks/>
    public bool DateBias {
        get {
            return this.dateBiasField;
        }
        set {
            this.dateBiasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExcludedGenericShow")]
    public string[] ExcludedGenericShow {
        get {
            return this.excludedGenericShowField;
        }
        set {
            this.excludedGenericShowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PreferredChannel")]
    public string[] PreferredChannel {
        get {
            return this.preferredChannelField;
        }
        set {
            this.preferredChannelField = value;
        }
    }
    
    /// <remarks/>
    public string log {
        get {
            return this.logField;
        }
        set {
            this.logField = value;
        }
    }
}
